# Generated by Django 3.0.5 on 2020-08-02 22:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetSuspenssions',
            fields=[
                ('suspension_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='suspension_id')),
                ('number_of_suspenssions', models.IntegerField(verbose_name='number_of_suspenssions')),
                ('asset_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets_users.Assets', verbose_name='asset_id')),
            ],
            options={
                'db_table': 'asset_suspenssions',
                'order_with_respect_to': 'suspension_id',
            },
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('registry_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='registry_id')),
                ('creation_date', models.DateField(auto_now=True)),
                ('creation_time', models.TimeField(default=django.utils.timezone.now)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets_users.Users')),
            ],
            options={
                'db_table': 'user_registration',
                'order_with_respect_to': 'user_id',
            },
        ),
        migrations.CreateModel(
            name='UserModification',
            fields=[
                ('modification_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='modification_id')),
                ('modifying_id', models.CharField(max_length=15, verbose_name='modifying_id')),
                ('modification_date', models.DateField(auto_now=True, verbose_name='modification_date')),
                ('modification_time', models.TimeField(default=django.utils.timezone.now)),
                ('justification', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets_users.Users', verbose_name='user_id')),
            ],
            options={
                'db_table': 'user_modification',
                'order_with_respect_to': 'user_id',
            },
        ),
        migrations.CreateModel(
            name='UnauthorizedIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('try_date', models.DateField(auto_now=True, verbose_name='try_date')),
                ('try_hour', models.TimeField(default=django.utils.timezone.now)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets_users.Users', verbose_name='user_id')),
            ],
            options={
                'db_table': 'unauthorized_income',
                'order_with_respect_to': 'user_id',
            },
        ),
        migrations.CreateModel(
            name='IncomesAndExits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_admission', models.DateField(auto_now=True, verbose_name='admission_date')),
                ('hour_admission', models.TimeField(verbose_name=django.utils.timezone.now)),
                ('departure_date', models.DateField(auto_now=True, verbose_name='departure_date')),
                ('departura_hour', models.TimeField(default=django.utils.timezone.now)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets_users.Users', verbose_name='user_id')),
            ],
            options={
                'db_table': 'incomes_and_exits',
                'order_with_respect_to': 'user_id',
            },
        ),
        migrations.CreateModel(
            name='AssetModification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modification_date', models.DateField(auto_now=True, verbose_name='modification_date')),
                ('modification_time', models.TimeField(verbose_name=django.utils.timezone.now)),
                ('justification', models.CharField(max_length=255)),
                ('asset_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets_users.Assets', verbose_name='asset_id')),
                ('modifying_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets_users.Users', verbose_name='modifying_id')),
            ],
            options={
                'db_table': 'asset_modification',
                'order_with_respect_to': 'asset_id',
            },
        ),
    ]
