# Generated by Django 3.0.5 on 2020-08-02 22:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmodification',
            name='modification_time',
            field=models.TimeField(default=datetime.time(22, 27, 32, 371009)),
        ),
        migrations.AlterField(
            model_name='incomesandexits',
            name='departura_hour',
            field=models.TimeField(default=datetime.time(22, 27, 32, 369498)),
        ),
        migrations.AlterField(
            model_name='incomesandexits',
            name='hour_admission',
            field=models.TimeField(default=datetime.time(22, 27, 32, 369448)),
        ),
        migrations.AlterField(
            model_name='unauthorizedincome',
            name='try_hour',
            field=models.TimeField(default=datetime.time(22, 27, 32, 370330)),
        ),
        migrations.AlterField(
            model_name='usermodification',
            name='modification_time',
            field=models.TimeField(default=datetime.time(22, 27, 32, 368543)),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='creation_time',
            field=models.TimeField(default=datetime.time(22, 27, 32, 367744)),
        ),
    ]
