# Generated by Django 3.0.5 on 2020-08-11 03:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auto_20200802_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmodification',
            name='modification_time',
            field=models.TimeField(default=datetime.time(21, 46, 16, 181971)),
        ),
        migrations.AlterField(
            model_name='incomesandexits',
            name='departura_hour',
            field=models.TimeField(default=datetime.time(21, 46, 16, 180283)),
        ),
        migrations.AlterField(
            model_name='incomesandexits',
            name='hour_admission',
            field=models.TimeField(default=datetime.time(21, 46, 16, 180237)),
        ),
        migrations.AlterField(
            model_name='unauthorizedincome',
            name='try_hour',
            field=models.TimeField(default=datetime.time(21, 46, 16, 181232)),
        ),
        migrations.AlterField(
            model_name='usermodification',
            name='modification_time',
            field=models.TimeField(default=datetime.time(21, 46, 16, 179095)),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='creation_time',
            field=models.TimeField(default=datetime.time(21, 46, 16, 178238)),
        ),
    ]
