# Generated by Django 3.0.5 on 2020-08-15 02:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_auto_20200811_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmodification',
            name='modification_time',
            field=models.TimeField(default=datetime.time(20, 19, 37, 962081)),
        ),
        migrations.AlterField(
            model_name='incomesandexits',
            name='departura_hour',
            field=models.TimeField(default=datetime.time(20, 19, 37, 960789)),
        ),
        migrations.AlterField(
            model_name='incomesandexits',
            name='hour_admission',
            field=models.TimeField(default=datetime.time(20, 19, 37, 960511)),
        ),
        migrations.AlterField(
            model_name='unauthorizedincome',
            name='try_hour',
            field=models.TimeField(default=datetime.time(20, 19, 37, 961487)),
        ),
        migrations.AlterField(
            model_name='usermodification',
            name='modification_time',
            field=models.TimeField(default=datetime.time(20, 19, 37, 959766)),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='creation_time',
            field=models.TimeField(default=datetime.time(20, 19, 37, 959082)),
        ),
        migrations.AlterOrderWithRespectTo(
            name='assetmodification',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='assetsuspenssions',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='incomesandexits',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='unauthorizedincome',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='usermodification',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='userregistration',
            order_with_respect_to=None,
        ),
    ]
