# Generated by Django 3.0.5 on 2020-08-15 03:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_auto_20200814_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmodification',
            name='modification_time',
            field=models.TimeField(default=datetime.time(21, 53, 43, 319698)),
        ),
        migrations.AlterField(
            model_name='incomesandexits',
            name='departura_hour',
            field=models.TimeField(default=datetime.time(21, 53, 43, 318395)),
        ),
        migrations.AlterField(
            model_name='incomesandexits',
            name='hour_admission',
            field=models.TimeField(default=datetime.time(21, 53, 43, 318193)),
        ),
        migrations.AlterField(
            model_name='unauthorizedincome',
            name='try_hour',
            field=models.TimeField(default=datetime.time(21, 53, 43, 319091)),
        ),
        migrations.AlterField(
            model_name='usermodification',
            name='modification_time',
            field=models.TimeField(default=datetime.time(21, 53, 43, 317469)),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='creation_time',
            field=models.TimeField(default=datetime.time(21, 53, 43, 316615)),
        ),
    ]
