# Generated by Django 3.0.5 on 2020-08-02 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('brand', models.CharField(db_index=True, max_length=255)),
                ('model', models.CharField(db_index=True, max_length=255)),
                ('useful_life', models.IntegerField(blank=True, null=True, verbose_name='useful_life')),
                ('cost', models.DecimalField(db_index=True, decimal_places=6, max_digits=8)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('admission_date', models.DateField(auto_now=True, db_index=True, verbose_name='admission_date')),
                ('actual_status', models.CharField(choices=[('A', 'activo'), ('B', 'baja'), ('S', 'suspendido')], db_index=True, max_length=1, verbose_name='actual_status')),
                ('provider', models.CharField(db_index=True, max_length=60)),
            ],
            options={
                'db_table': 'assets',
                'order_with_respect_to': 'code',
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='department_id')),
                ('name', models.CharField(max_length=60)),
                ('creation_date', models.DateField(auto_now=True, verbose_name='create_date')),
                ('staff_amount', models.IntegerField(blank=True, null=True, verbose_name='staff_amount')),
            ],
            options={
                'db_table': 'departments',
                'order_with_respect_to': 'department_id',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('identification_card', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='identification_card')),
                ('name', models.CharField(max_length=255)),
                ('surnames', models.CharField(max_length=255)),
                ('phone', models.CharField(db_index=True, max_length=14, unique=True)),
                ('age', models.CharField(max_length=2)),
                ('status', models.BooleanField(default=False)),
                ('admission_date', models.DateField(auto_now=True, db_index=True, verbose_name='admission_date')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets_users.Departments')),
            ],
            options={
                'db_table': 'users',
                'order_with_respect_to': 'identification_card',
            },
        ),
        migrations.CreateModel(
            name='UserSuspensions',
            fields=[
                ('suspension_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='suspension_id')),
                ('number_of_suspenssions', models.IntegerField(verbose_name='number_of_suspenssions')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets_users.Users')),
            ],
            options={
                'db_table': 'user_suspensions',
                'order_with_respect_to': 'suspension_id',
            },
        ),
        migrations.CreateModel(
            name='UsersAssets',
            fields=[
                ('id_user_asset', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='id_user_asset')),
                ('asset_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets_users.Assets', verbose_name='asset_id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets_users.Users', verbose_name='user_id')),
            ],
            options={
                'db_table': 'users_assets',
                'order_with_respect_to': 'id_user_asset',
            },
        ),
        migrations.CreateModel(
            name='Depreciations',
            fields=[
                ('depreciation_code', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='depreciation_code')),
                ('depreciation', models.DecimalField(db_index=True, decimal_places=6, max_digits=8)),
                ('assets_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets_users.Assets', verbose_name='assets_code')),
            ],
            options={
                'db_table': 'depreciations',
                'order_with_respect_to': 'depreciation_code',
            },
        ),
        migrations.CreateModel(
            name='AccumulatedMoney',
            fields=[
                ('accumulated_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='accumulated_id')),
                ('accumulated', models.DecimalField(decimal_places=6, max_digits=8)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets_users.Users')),
            ],
            options={
                'db_table': 'accumulated_money',
                'order_with_respect_to': 'accumulated_id',
            },
        ),
    ]
