# Generated by Django 3.0.5 on 2020-09-08 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets_users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersAssets',
        ),
    ]
