# Generated by Django 3.0.5 on 2020-08-11 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='assets',
            order_with_respect_to=None,
        ),
    ]
