# Generated by Django 3.0.5 on 2020-08-15 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets_users', '0002_auto_20200810_2146'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='accumulatedmoney',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='departments',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='depreciations',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='users',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='usersassets',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='usersuspensions',
            order_with_respect_to=None,
        ),
    ]
