# Generated by Django 3.0.5 on 2020-09-09 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_users', '0003_assets_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='actual_status',
            field=models.CharField(db_index=True, max_length=30, verbose_name='actual_status'),
        ),
    ]
