# Generated by Django 3.0.5 on 2020-08-02 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='report_id')),
                ('creation_date', models.DateField(auto_now=True, db_index=True, verbose_name='creation_date')),
                ('affair', models.CharField(max_length=255)),
                ('desciption', models.CharField(max_length=255)),
                ('receiving_mail', models.EmailField(max_length=254)),
                ('status', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets_users.Users', verbose_name='user_id')),
            ],
            options={
                'db_table': 'reports',
                'order_with_respect_to': 'report_id',
            },
        ),
    ]
