# Generated by Django 3.0.5 on 2020-08-15 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='reports',
            order_with_respect_to=None,
        ),
    ]
